{% set name = "vifm" %}
{% set version = "0.10.1" %}
{% set sha256 = "99006f56db05e1bdfb7983e8d5c31c9ac93bf2ac9e0409a577c8ca660fecd03b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://jaist.dl.sourceforge.net/project/vifm/vifm/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - ncurses

  run:
    - ncurses

test:
  commands:
    - vifm --help

about:
  home: https://vifm.info/
  license: GPL-2.0
  license_file: COPYING
  summary: Vifm is an ncurses based file manager with vi like keybindings

extra:
  recipe-maintainers:
    - Rex-Diego
