{% set name = "vifm" %}
{% set version = "0.14.2" %}
{% set sha256 = "cd1b05d2543cdf6829d60b23bc225c6fde13d3ef7c1008f821b9209837f1e2b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://jaist.dl.sourceforge.net/project/vifm/vifm/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - ncurses

  run:
    - ncurses

test:
  commands:
    - vifm --help

about:
  home: https://vifm.info/
  license: GPL-2.0
  license_file: COPYING
  summary: 'Vifm is an ncurses based file manager with vi like keybindings'

extra:
  recipe-maintainers:
    - Rex-Diego
