travis:
  secure:
    BINSTAR_TOKEN: P6pAqr7JnVsOs9x8c1J2HyITEwBlBifD1SYQcubkDW5bT3moIW+d+hADPqONRzdqJYFnPba03QBX/nKk9Kq+Qqj/LFJYlEwTn7Ji/ZD3FRJSCjtVtH7gYI25sE0N/V8qfjgB6B8P4VW/ZEX8xHXP8ecGgg0pPR8ZL+3oGm9SAAqTTXM/7UlHGrdZcHFB3dAkhkktJEXvChDKuBYzcFso+z78SXj0FPmlLKMgA9jFji79FAcE/M/ahP3bCqiGnjDGFVycpd9+0MGq+FyhsdThi+fNEd0hXw1Fnn1sOH9ZOGlqmPy7dYcRsZl8MCf1IUTECUW9exYObaFtxicJ3Pu0FIUKTDwDHQdMMyAzI/7DxucnjWGIP5SmfMZNdrcraaX50UgxMnYlARHQNQHwRnRvYt48sfvWgSNDXiDvgPDkL9KTM3Q1cJfdiAhhTBkb7NFgaQdVajJ5wsDDtvDnDU2Eg7XJxwI2ekGycEJ1p9cWx/n8A2iaiYvUd2D/E+SKEw1z3ICTj30TwHcY8U0pohXwNXjQp7+62b2SBNXNIWnx+nAC0dVdg0OjnU+lQR5Y2BapG35WSj9sUXj9F+m7DIAUcH14wQAKK7PJ1Jm7XVIxziiCxMlDxg80IC9ow2nzDqyE3I/E0z3R5ZTM5M8f3lMRN9p5XnS6GKcByjwI5Yv5ItQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
