travis:
  secure:
    BINSTAR_TOKEN: RC6sIB290GpTFxXwblD2mqtj8hOYnLQAAQKifXrhfS/+e15B7OXrWcDHWJRzg1O03mZ436CtZWhPvCPqz1PG7PzQYH7Yzl/6jwwaO2L6uqFTHH4Olqw8b5wFtzb4o0aO/yu88nAcpRzpKPiImi9XPPHVnsDv0sA+vhuNkIxILNCmvxi3fWPlzkVmN6+Pqf9PrXpv7+zbKu1GmIMATuC3c2MA+U9kZGeOFtA30aVxDnhrd+zaBI3CTZjqzD/ryg9DIT07SFLgtnEA7/5PXnSpIDkKQWjt6MfWupufoAbUI89k4WqAWF0kdX3T/8W9L92timBpabVbsT0SIpTXa9oyLrBs3CR+OTIB0sDjNliNquLH9ZJwA6rv0577xvlf83jJqIwtzsyZcBNJPjY3kMSEdGG2fbFIJTtPqtkaFOdwuJcQjGCNVcY1gKsRfAuOlzkbPjBN8/iAgL1567+bLb2oBpGKLdP1UnvzfJE5RvmmkfMMXBsp+ucney0IFNtsAOiFORjktHLmVbRIxFsiJNpm4H7A+nuRZXVAMmOeOT1iwBi3pzjhJxV+cXM+VK2jPB0/bO/ssOmaVV2MRtfIt5Ta8bWVzSZdajAXXof91dqlFbtyH8yLrrvGEvs9Jy1ikB91/xGlfF/bv3BEC0KtNVMrXiA4PikrHJd/ab70wm2URUA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
